version: '3'
services:
  postgres-db:
    image: postgres
    environment:
      POSTGRES_USER: mfshair01
      POSTGRES_PASSWORD: Mshair01
      POSTGRES_DB: collaborative_code_editor
    ports:
      - "5432:5432"
    networks:
      - app-network

  collaborative-code-editor:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/collaborative_code_editor
      SPRING_DATASOURCE_USERNAME: mfshair01
      SPRING_DATASOURCE_PASSWORD: Mshair01
    ports:
      - "8081:8080"
    depends_on:
      - postgres-db
    networks:
      - app-network

networks:
  app-network:
